services:
  bridge-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridge-server
    restart: no
    ports:
      - "50051:50051"
    environment:
      - PKEY=${PKEY}
    volumes:
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
